name: Python CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        run: sudo apt-get install python3 -y

      - name: Run Python App
        run: python3 app.py
